# Generated by Django 4.0.6 on 2022-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField(max_length=1000)),
                ('shorturl', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
